### ISSUE TITLE
For 2.0

### ISSUE THREAD

**Issue by AdventureOfMar** [imaginary-cloud/CameraManager#16]
'stringByAppendingPathExtension' is unavailable: Use URLByAppendingPathExtension on NSURL instead.

**Comment by nelanelanela** [comment]
Wow, nice timing, I just pushed the changes :D

**Comment by cohix** [comment]
I'm still getting this error in the 2.0 version of the pod :( not sure why. The source still uses stringByAppendingPathExtension. Is there a different pod version I should be using? @nelanelanela

**Comment by cohix** [comment]
I changed it to use the git repo directly and it's fine. I'm not sure how cocoapods works but it doesn't seem to be in sync with the git repo!
