### ISSUE TITLE
When flash is on, app is crashing in capturePictureWithCompletion

### ISSUE THREAD

**Issue by vkhattar** [imaginary-cloud/CameraManager#56]
This is error I am seeing, domain: "AVFoundationErrorDomain" - code: 11800. 

It was working before, even currently works without the flash functionality. Not sure as to what happened. 

Just fixed the issue, its not specific to CameraManager, but heads up for people using a segue on taking a picture, it will work without flash but will break if flash is on. Need to make the capture button link to the action instead of prepareForSegue.

**Comment by torrao** [comment]
@vkhattar 

this should be fixed in v3.1.4. Thanks 👍

**Comment by mabuak** [comment]
I thinks this bug still not fixed, i'm still got that issue


<img width="595" alt="screen shot 2018-09-20 at 16 29 19" src="https://user-images.githubusercontent.com/15919105/45809464-71abeb80-bcf2-11e8-9c88-639355284046.png">

I'm used version 4.3.
